app/manager/urls.py
from django.conf.urls import patterns, url, include
from django.core.urlresolvers import reverse_lazy
from manager.views import *

manager_urls = patterns(
    '',
    url(r'^$', ListTrendView.as_view(), name="manager_home"),
    url(r'^trend/edit/(?P<pk>[-\w]+)/$', TrendUpdateView.as_view(success_url=reverse_lazy('manager:manager_home')),
        name='manager_trend_list'),
    url(r'^trend/add/$', TrendCreateView.as_view(success_url=reverse_lazy('manager:manager_home')),
        name='manager_trend_add'),

)

api_manager_urls = patterns(
    '',
    url(r'^create/', createtop, name='create+api'),
)

zamly/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin
from manager.urls import api_manager_urls, manager_urls
from core.views import *

api_packages_urls = patterns(
    '',
    url(r'^tweets/top/(?P<name>[^/]+)/', TopTweetsDetail.as_view()),
    url(r'^tweets/top/w/(?P<name>[^/]+)/', TopTweetsWordsDetail.as_view()),
    url(r'^tweets/updates/(?P<id_tweet>\d+)/', UpdatesDetail.as_view()),
    url(r'^tweets/(?P<id_tweet>\d+)/', TweetsDetail.as_view()),
)

api_urls = patterns(
    '',
    url(r'^api/v1/', include(api_packages_urls, namespace='api')),
    url(r'^api/v1/manager/', include(api_manager_urls, namespace='api_manager')),
)

urlpatterns = patterns(
    '',
    url(r'^info', info, name='info'),
    url(r'^manager/', include(manager_urls, namespace='manager')),
    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += api_urls

app/manager/views.py
import json
import random
from time import timezone
from django.conf import settings
from django.http import HttpResponse
from django.shortcuts import redirect
from django.views.generic import ListView, UpdateView, CreateView
from twitter import Twitter, OAuth
from core.models import Trends, Tweet, RelatedTweets, TopTweets
from ttp import ttp
from core.utils import groups_tweets, proccess_tweets


class ListTrendView(ListView):
    model = Trends
    template_name = "manager/trend_list.html"

    def get_context_data(self, **kwargs):
        context = super(ListTrendView, self).get_context_data(**kwargs)
        return context

    def dispatch(self, *args, **kwargs):
        if not self.request.user.is_staff:
                return redirect('manager:manager_home')
        return super(ListTrendView, self).dispatch(*args, **kwargs)

class TrendUpdateView(UpdateView):
    model = Trends
    fields = '__all__'
    template_name = "manager/trend_update.html"

    def dispatch(self, *args, **kwargs):
        if not self.request.user.is_staff:
                return redirect('manager:manager_home')
        return super(TrendUpdateView, self).dispatch(*args, **kwargs)

class TrendCreateView(CreateView):
    model = Trends
    fields = '__all__'
    template_name = "manager/trend_add.html"

    def dispatch(self, *args, **kwargs):
        if not self.request.user.is_staff:
                return redirect('manager:manager_home')
        return super(TrendCreateView, self).dispatch(*args, **kwargs)

def createtop(request):
    success = False
    counter = 0

    try:
      trend = Trends.objects.get(id=request.GET['trend'])
      twitter = Twitter(
      auth=OAuth(settings.TOKEN, settings.TOKEN_KEY, settings.CON_SECRET, settings.CON_SECRET_KEY))

      if trend.is_hastag:
          items = twitter.search.tweets(q="#"+trend.name,result_type='recent',count='100')
          proccess_tweets(trend,items)
          items = twitter.search.tweets(q="#"+trend.name,result_type='popular',count='20')
          proccess_tweets(trend,items)
      else:
          items = twitter.search.tweets(q=trend.name,result_type='recent',count='100')
          proccess_tweets(trend,items)
          items = twitter.search.tweets(q=trend.name,result_type='popular',count='20')
          proccess_tweets(trend,items)


      tweets = Tweet.objects.filter(trend=trend)
      if tweets.count() >= 100:
        obj = TopTweets.objects.create(trend=trend)
        i = 1
        for tweet in tweets:
            tweet.place = i
            tweet.save()
            obj.tweets.add(tweet)
            obj.save()
            i += 1
        obj.is_active = True
        obj.save()

        groups_tweets([s.id for s in tweets])

        success = True
      else:
          success = False
          counter = tweets.count()
    except:
        success = False

    data_to_dump = {
        'success': success,
        'counter': counter
    }
    data = json.dumps(data_to_dump)
    res = HttpResponse(data, content_type='application/json; charset=utf-8')
    return res

templates/manager/base.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% include 'manager/style.html' %}
</head>
<body>
<div class="container">
{% block content %}

{% endblock %}
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<script>
$(document).ready(function(){
  $('.create').on('click', function() {
      var trend = $(this).data('id');

      $('.preloader_center').show();

      $.ajax({
        type: "GET",
        url: "/api/v1/manager/create",
        data: "trend="+trend,
        success: function(data){
            console.log(data['success']);
            if(data['success']){
                $('.add_top_'+trend).append('<p class="btn btn-info">Топ создан обновите страницу!</p>');
                $('.preloader_center').hide();
            }
            else{
                if(data['counter'] !=0){
                    $('.add_top_'+trend)
                            .append('<p class="btn btn-info">Твитов добавлено '+data['counter']+'' +
                            ', Попробуйте еще раз через минуту!</p>');
                    $('.preloader_center').hide();
                }
                else{
                    $('.add_top_'+trend).append('<p class="btn btn-danger">Что-то пошло не так. Ошибка!</p>');
                    $('.preloader_center').hide();
                }

            }
        }
      });

  });
});
</script>
</body>
</html>

templates/manager/trend_add.html
{% extends 'manager/base.html' %}

{% block title %}Add trend{% endblock %}

{% block content %}
<div class="bs-example" data-example-id="basic-forms">
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input class="btn btn-success" type="submit" value="Add" />
</form>
</div>
{% endblock %}

templates/manager/trend_list.html
{% extends 'manager/base.html' %}

{% block title %}Trends List{% endblock %}

{% block content %}
<br>
<div class="bs-example" data-example-id="striped-table">

<div class="preloader_center" style="display: none">
	<div class="preloader">
            <div class="item item_1"></div>
            <div class="item item_2"></div>
            <div class="item item_3"></div>
    </div>
</div>

<a class="btn btn-danger" href="{% url 'manager:manager_trend_add' %}">Добавить тренд</a>

{% if object_list %}
<table class="table table-striped">
      <thead>
        <tr>
          <th>ID</th>
          <th>Edit</th>
          <th>Name</th>
          <th>Active</th>
          <th>Hastag</th>
          <th>Is Top</th>
          <th>Watch Top</th>
          <th>Created</th>
        </tr>
      </thead>
      <tbody>
        {% for tr in object_list %}
        <tr>
          <th scope="row">{{ tr.id }}</th>
            <td><a class="btn btn-warning" href="{% url 'manager:manager_trend_list' tr.id %}">Edit</a></td>
            <td>{% if tr.is_hastag %}#{{ tr.name }}{% else %}{{ tr.name }}{% endif %}</td>
            <td>{{ tr.is_active }}</td>
            <td>{{ tr.is_hastag }}</td>
            <td class="add_top_{{ tr.id }}">
                {% if tr.is_top %}
                    <p class="btn btn-primary">[Кол. {{ tr.is_top }}] Обновить топ</p>
                {% else %}
                    <p class="btn btn-success create" data-id="{{ tr.id }}">Создать топ</p>
                {% endif %}
            </td>
            <td>{% if tr.is_top %}
               {% if tr.is_hastag %}
                    <a target="_blank" href="http://twizoom.com/{{ tr.name }}/top" class="btn btn-info">
                        Посмотреть топ #{{ tr.name }}
                    </a>
                {% else %}
                    <a target="_blank" href="http://twizoom.com/w/{{ tr.name }}/top" class="btn btn-info">
                        Посмотреть топ {{ tr.name }}
                    </a>
                {% endif %}
                {% endif %}
            </td>
            <td>{{ tr.created|date:"j/n/Y H:i:s" }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
</div>

{% else %}
   <p class="btn btn-danger">Трендов еще нет! Добавьте!</p>
{% endif %}
{% endblock %}

templates/manager/trend_update.html
{% extends 'manager/base.html' %}

{% block title %}Update List{% endblock %}

{% block content %}
<div class="bs-example" data-example-id="basic-forms">
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input class="btn btn-success" type="submit" value="Update" />
</form>
</div>
{% endblock %}